Exception on /api/user/user_info [POST]
Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 246, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Unknown MySQL server host 'db host' (8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 83, in view
    self = view.view_class(*class_args, **class_kwargs)  # type: ignore
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/controller/controller.py", line 11, in __init__
    self.service = UserService()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/service/service.py", line 7, in __init__
    self.dao = UserDAO()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/dao/dao.py", line 9, in __init__
    self.db = DB()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/common_lib/infra/mysql.py", line 32, in __init__
    DB._connection_pool = MySQLConnectionPool(host=DB.mysql_host,
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/pooling.py", line 179, in __init__
    self.add_connection()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/pooling.py", line 290, in add_connection
    cnx = Connect(**self._cnx_config)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/__init__.py", line 272, in connect
    return CMySQLConnection(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 94, in __init__
    self.connect(**kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/abstracts.py", line 1052, in connect
    self._open_connection()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 251, in _open_connection
    raise errors.get_mysql_exception(msg=exc.msg, errno=exc.errno,
mysql.connector.errors.DatabaseError: 2005 (HY000): Unknown MySQL server host 'db host' (8)
Exception on /api/user/user_info [POST]
Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/controller/controller.py", line 14, in post
    validate = UserInfo.Schema().load(request.get_json(force=True, silent=True))
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/marshmallow_dataclass/__init__.py", line 638, in load
    all_loaded = super().load(data, many=many, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'email': ['Missing data for required field.'], 'first_name': ['Missing data for required field.'], 'prof_pic_url': ['Missing data for required field.'], 'last_name': ['Missing data for required field.']}
Exception on /api/user/user_info [POST]
Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 535, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'feed2f1d-5985-4c61-9034-a75a637e4b00''' at line 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/common_lib/infra/mysql.py", line 65, in cursor
    yield cursor
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/dao/dao.py", line 22, in get_user
    cursor.execute(query, {
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 269, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 540, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'feed2f1d-5985-4c61-9034-a75a637e4b00''' at line 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 626, in statement
    return self._executed.strip().decode('utf8')
AttributeError: 'NoneType' object has no attribute 'strip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/controller/controller.py", line 15, in post
    user_info = self.service.get_user(validate)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/service/service.py", line 10, in get_user
    return self.dao.get_user(req.user_id)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/dao/dao.py", line 34, in get_user
    return user
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/common_lib/infra/mysql.py", line 68, in cursor
    if cursor.statement:
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 628, in statement
    return self._executed.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
Exception on /api/user/user_info [POST]
Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 535, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'feed2f1d-5985-4c61-9034-a75a637e4b00''' at line 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/common_lib/infra/mysql.py", line 65, in cursor
    yield cursor
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/dao/dao.py", line 22, in get_user
    cursor.execute(query, {
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 269, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 540, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'feed2f1d-5985-4c61-9034-a75a637e4b00''' at line 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 626, in statement
    return self._executed.strip().decode('utf8')
AttributeError: 'NoneType' object has no attribute 'strip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/controller/controller.py", line 15, in post
    user_info = self.service.get_user(validate)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/service/service.py", line 10, in get_user
    return self.dao.get_user(req.user_id)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/dao/dao.py", line 22, in get_user
    cursor.execute(query, {
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/common_lib/infra/mysql.py", line 68, in cursor
    if cursor.statement:
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 628, in statement
    return self._executed.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
Exception on /api/user/user_info [POST]
Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 535, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'feed2f1d-5985-4c61-9034-a75a637e4b00''' at line 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/common_lib/infra/mysql.py", line 65, in cursor
    yield cursor
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/dao/dao.py", line 22, in get_user
    cursor.execute(query, {
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 269, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 540, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'feed2f1d-5985-4c61-9034-a75a637e4b00''' at line 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 626, in statement
    return self._executed.strip().decode('utf8')
AttributeError: 'NoneType' object has no attribute 'strip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/controller/controller.py", line 15, in post
    user_info = self.service.get_user(validate)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/service/service.py", line 10, in get_user
    return self.dao.get_user(req.user_id)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/dao/dao.py", line 22, in get_user
    cursor.execute(query, {
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/common_lib/infra/mysql.py", line 68, in cursor
    if cursor.statement:
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 628, in statement
    return self._executed.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
Exception on /api/user/user_info [POST]
Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 535, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'feed2f1d-5985-4c61-9034-a75a637e4b00''' at line 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/common_lib/infra/mysql.py", line 65, in cursor
    yield cursor
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/dao/dao.py", line 22, in get_user
    cursor.execute(query, {
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 269, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 540, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'feed2f1d-5985-4c61-9034-a75a637e4b00''' at line 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 626, in statement
    return self._executed.strip().decode('utf8')
AttributeError: 'NoneType' object has no attribute 'strip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/controller/controller.py", line 15, in post
    user_info = self.service.get_user(validate)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/service/service.py", line 10, in get_user
    return self.dao.get_user(req.user_id)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/dao/dao.py", line 22, in get_user
    cursor.execute(query, {
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/common_lib/infra/mysql.py", line 68, in cursor
    if cursor.statement:
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 628, in statement
    return self._executed.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
Exception on /api/user/user_info [POST]
Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 535, in cmd_query
    self._cmysql.query(query,
_mysql_connector.MySQLInterfaceError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'feed2f1d-5985-4c61-9034-a75a637e4b00''' at line 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/common_lib/infra/mysql.py", line 65, in cursor
    yield cursor
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/dao/dao.py", line 22, in get_user
    cursor.execute(query, {
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 269, in execute
    result = self._cnx.cmd_query(stmt, raw=self._raw,
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/connection_cext.py", line 540, in cmd_query
    raise errors.get_mysql_exception(exc.errno, msg=exc.msg,
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'feed2f1d-5985-4c61-9034-a75a637e4b00''' at line 7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 626, in statement
    return self._executed.strip().decode('utf8')
AttributeError: 'NoneType' object has no attribute 'strip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/controller/controller.py", line 15, in post
    user_info = self.service.get_user(validate)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/service/service.py", line 10, in get_user
    return self.dao.get_user(req.user_id)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/dao/dao.py", line 22, in get_user
    cursor.execute(query, {
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/common_lib/infra/mysql.py", line 68, in cursor
    if cursor.statement:
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/mysql/connector/cursor_cext.py", line 628, in statement
    return self._executed.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
Exception on /api/user/user_info [POST]
Traceback (most recent call last):
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/.venv/lib/python3.8/site-packages/flask/views.py", line 158, in dispatch_request
    return current_app.ensure_sync(meth)(*args, **kwargs)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/controller/controller.py", line 15, in post
    user_info = self.service.get_user(validate)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/service/service.py", line 10, in get_user
    return self.dao.get_user(req.user_id)
  File "/Users/kyle/Documents/Dev/chatapp-backend-template/chatapp/users/dao/dao.py", line 26, in get_user
    user = UserInfo(
TypeError: __init__() got an unexpected keyword argument 'id'
